### PR TITLE
Verify the status of the deployment before returning from the task

### LINKED ISSUE #20: Verify deployment status and print errors if any
### What feature do you want to see added?

The publish task should wait for the successful deployment and it should fail should the deploy fail.
See https://central.sonatype.org/publish/publish-portal-api/#verify-status-of-the-deployment

### Upstream changes

_No response_

### Are you interested in contributing this feature?

_No response_

### PR DESCRIPTION
**Pull request by martinbonnin**
Closes #20 

Error:

```
> Task :publishAggregatedPublicationToCentralPortal
Nmcp: deployment bundle 'b772ce8d-407e-4664-b11c-e39ed3c74d36' uploaded.
Nmcp: verifying deployment status...
Deployment has failed:
{"pkg:maven/net.mbonnin.tnmcp/module1@0.0.3":["Missing signature for file: module1-0.0.3-javadoc.jar","Missing signature for file: module1-0.0.3-sources.jar","Missing signature for file: module1-0.0.3.jar","Missing signature for file: module1-0.0.3.module","Missing signature for file: module1-0.0.3.pom"],"pkg:maven/net.mbonnin.tnmcp/module2@0.0.3":["Missing signature for file: module2-0.0.3-javadoc.jar","Missing signature for file: module2-0.0.3-sources.jar","Missing signature for file: module2-0.0.3.jar","Missing signature for file: module2-0.0.3.module","Missing signature for file: module2-0.0.3.pom"]}
```

Success:

```
> Task :publishAggregatedPublicationToCentralPortal
Nmcp: deployment bundle '71468e66-bac9-42f4-866f-1ffb5c2f76a7' uploaded.
Nmcp: verifying deployment status...
Deployment has passed validation, publish it manually from the Central Portal UI

BUILD SUCCESSFUL in 26s
```

### CODE REVIEW

File: src/main/kotlin/nmcp/NmcpAggregation.kt [hunk 1]
```diff
@@ -9,12 +9,45 @@ abstract class NmcpAggregation @Inject constructor(
     private val configuration: Configuration,
     private val project: Project,
     ) {
+    /**
+     * The central portal username
+     */
     abstract val username: Property<String>
+
+    /**
+     * The central portal username
```
Comment (vlsi) [inline src/main/kotlin/nmcp/NmcpAggregation.kt:18]: Password

File: src/main/kotlin/nmcp/NmcpPublishTask.kt [hunk 2]
```diff
@@ -62,23 +70,111 @@ abstract class NmcpPublishTask : DefaultTask() {
...
                 }
+
+                it.body!!.string()
             }
+
+        logger.lifecycle("Nmcp: deployment bundle '$deploymentId' uploaded.")
+
+        if (verifyStatus.get()) {
+            logger.lifecycle("Nmcp: verifying deployment status...")
+            while (true) {
```
Comment (vlsi) [inline src/main/kotlin/nmcp/NmcpPublishTask.kt:94]: It would be nice to configure a timeout with default being 5 or 10 minutes

File: src/main/kotlin/nmcp/NmcpSpec.kt [hunk 3]
```diff
@@ -3,9 +3,42 @@ package nmcp
 import org.gradle.api.provider.Property
 
 abstract class NmcpSpec {
+    /**
+     * The central portal username
+     */
     abstract val username: Property<String>
+
+    /**
+     * The central portal username
```
Comment (vlsi) [inline src/main/kotlin/nmcp/NmcpSpec.kt:12]: password

File: src/main/kotlin/nmcp/NmcpPublishTask.kt (hunk 2 above)
Comment (martinbonnin) [reply src/main/kotlin/nmcp/NmcpPublishTask.kt:94]: Added in https://github.com/GradleUp/nmcp/pull/27
